version: '3.9'

services:
  cache:
    image: redis:7.4.1
    container_name: cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache_data:/cache_data

volumes:
  cache_data: